In [3]:
import pandas as pd

df = pd.read_csv('kkbox_data/kkbox_data.csv')
df.head()

,rank,artist,artist_id,song_id,album_id,date,category
0,1,五月天 (Mayday),9XN-7yg5vg3gYnCdsM,5_DAFKxzMf04hZqXk4,0le7fKde-BNMwoAst3,2021-01-01,mandarin
1,2,盧廣仲 (Crowd Lu),8qCONzjl89Yak9KFxZ,L_Aag3up_NyBpahTJG,4rzv06iAFoOyareMC7,2021-01-01,mandarin
2,3,任然,#,#,#,2021-01-01,mandarin
3,4,艾薇,SkYfuVHgT10-nfv3Tz,XXONe3fIN4kbrmzJqh,XXDPJ346EjhjDZXb-W,2021-01-01,mandarin
4,5,aMEI (張惠妹),Ok6kf9NM0d0grGYNbl,P_c_y1B6adNriKJkm6,Okl8SAlaH9M2s97GAv,2021-01-01,mandarin

In [4]:
artist = df[df['artist_id'] != '#'][['artist', 'artist_id']].drop_duplicates()
artist

                    artist           artist_id
0             五月天 (Mayday)  9XN-7yg5vg3gYnCdsM
1           盧廣仲 (Crowd Lu)  8qCONzjl89Yak9KFxZ
3                       艾薇  SkYfuVHgT10-nfv3Tz
4               aMEI (張惠妹)  Ok6kf9NM0d0grGYNbl
5          周興哲 (Eric Chou)  TZghSjbKIgUdp9HKxN
...                    ...                 ...
8772  Clean Bandit (清潔的盜賊)  9aBikN_q8L4IkdIm_D
8780    黃玠瑋 (Zooey Wonder)  OnwVHd4Ue0DkM4hMxA
8788            Pale Waves  9a1cN2_q8L4ImuCl-p
8798              Doja Cat  HX0MYLKP8cmeEl4dKA
9075     Alan Walker, ISÁK  KkuCLalynYMj8NYgrU

[231 rows x 2 columns]